// Généré depuis shazmila_52_planches.html — NE PAS éditer à la main.
// Collection « Instants de Motivation — Shazmila et ses amis » : 52 planches BD,
// une par semaine, présentées en carnet ePub feuilletable (6 cases = 6 pages).

export type PlancheInfo = { n: number; titre: string };

/** Les 52 planches (n = numéro de semaine dans la collection, 1..52). */
export const PLANCHES: PlancheInfo[] = [
  { n: 1, titre: "C'est la rentrée !" },
  { n: 2, titre: "Bienvenue, la nouvelle !" },
  { n: 3, titre: "Merci, chers enseignants !" },
  { n: 4, titre: "Deux oreilles, une bouche" },
  { n: 5, titre: "Des mains propres, une santé de fer" },
  { n: 6, titre: "Bien manger pour bien apprendre" },
  { n: 7, titre: "Le courage de demander" },
  { n: 8, titre: "Non au harcèlement !" },
  { n: 9, titre: "Encore un essai !" },
  { n: 10, titre: "Nos droits, nos ailes" },
  { n: 11, titre: "La gentillesse est contagieuse" },
  { n: 12, titre: "L'écran n'est pas mon maître" },
  { n: 13, titre: "Le tutorat des copains" },
  { n: 14, titre: "Mon bilan de l'année" },
  { n: 15, titre: "Donner, même un sourire" },
  { n: 16, titre: "La famille, mon premier village" },
  { n: 17, titre: "Une nouvelle page" },
  { n: 18, titre: "Le secret des petits pas" },
  { n: 19, titre: "Mon emploi du temps magique" },
  { n: 20, titre: "Les mots magiques" },
  { n: 21, titre: "Pourquoi ? Pourquoi ?" },
  { n: 22, titre: "Un ami, un trésor" },
  { n: 23, titre: "Partager, c'est multiplier" },
  { n: 24, titre: "Propre comme un sou neuf" },
  { n: 25, titre: "Les filles aussi !" },
  { n: 26, titre: "Je suis capable !" },
  { n: 27, titre: "Ensemble, on va plus loin" },
  { n: 28, titre: "Le voyage immobile" },
  { n: 29, titre: "Notre planète, notre maison" },
  { n: 30, titre: "La vérité, même quand c'est dur" },
  { n: 31, titre: "Vive les erreurs !" },
  { n: 32, titre: "Chaque chose en son temps" },
  { n: 33, titre: "Merci !" },
  { n: 34, titre: "Ma tête est une usine à idées" },
  { n: 35, titre: "L'effort d'abord, le jeu ensuite" },
  { n: 36, titre: "Réviser sans pleurer" },
  { n: 37, titre: "Maman, ma première maîtresse" },
  { n: 38, titre: "Respire, Shazmila !" },
  { n: 39, titre: "Le jour J" },
  { n: 40, titre: "Papa, mon héros silencieux" },
  { n: 41, titre: "Tomber sept fois, se relever huit" },
  { n: 42, titre: "Bravo à tous !" },
  { n: 43, titre: "Des vacances intelligentes" },
  { n: 44, titre: "Ma bibliothèque de l'été" },
  { n: 45, titre: "Coup de main à la maison" },
  { n: 46, titre: "Quand je serai grande…" },
  { n: 47, titre: "Un rêve, un plan" },
  { n: 48, titre: "Tous différents, tous précieux" },
  { n: 49, titre: "Dormir pour grandir" },
  { n: 50, titre: "La discipline, ma meilleure alliée" },
  { n: 51, titre: "La solidarité, notre force" },
  { n: 52, titre: "Demain commence aujourd'hui" },
];
